import { useCallback, useEffect, useMemo, useState } from "react";
import { Edit, ImageOff } from "lucide-react";
import { adminRequest, adminUpdateProduct } from "../lib/api";
export default function AdminCollectionTiles(){
 const [products,setProducts]=useState([]),[tiles,setTiles]=useState([]),[tileProducts,setTileProducts]=useState({}),[open,setOpen]=useState(null),[query,setQuery]=useState(""),[error,setError]=useState("");
 const load=useCallback(async()=>{try{const [all,collectionTiles]=await Promise.all([adminRequest("/admin/products"),adminRequest("/admin/collection-tiles")]);setProducts(all);setTiles(collectionTiles);const rows=await Promise.all(["pearls","gold","ocean"].map(async key=>[key,await adminRequest("/admin/tile-products/"+key)]));setTileProducts(Object.fromEntries(rows));}catch(e){setError(e.message);}},[]);
 useEffect(()=>{load();},[load]); const matches=useMemo(()=>products.filter(p=>!query||p.name.toLowerCase().includes(query.toLowerCase())||p.slug.toLowerCase().includes(query.toLowerCase())).slice(0,30),[products,query]);
 const add=async product=>{try{await adminRequest("/admin/tile-products",{method:"POST",body:JSON.stringify({tile_key:open,product_id:product.id,sort_order:(tileProducts[open]||[]).length})});setOpen(null);setQuery("");load();}catch(e){setError(e.message);}};
 const remove=async id=>{try{await adminRequest("/admin/tile-products/"+id,{method:"DELETE"});load();}catch(e){setError(e.message);}};
 const saveLabel=async(tileKey,label)=>{try{const updated=await adminRequest("/admin/collection-tiles/"+tileKey,{method:"PUT",body:{label}});setTiles(current=>current.map(tile=>tile.tile_key===updated.tile_key?updated:tile));}catch(e){setError(e.message);}};
 return <div className="max-w-5xl"><div className="mb-8"><p className="text-[10px] uppercase tracking-[.28em] text-gold">Homepage curation</p><h1 className="font-display text-4xl text-cocoa mt-2">Collection Tiles</h1><p className="mt-2 text-sm text-cocoa/60">Edit the customer-facing label and manage the products shown on each tile.</p></div>{error&&<p className="mb-4 text-sm text-cocoa">{error}</p>}<div className="grid gap-5 md:grid-cols-3">{["pearls","gold","ocean"].map(key=><section key={key} className="border border-cocoa/10 bg-shell p-5"><TileLabelForm tile={tiles.find(tile=>tile.tile_key===key)} onSave={saveLabel}/><div className="mt-4 space-y-2">{(tileProducts[key]||[]).map(p=><div key={p.tile_product_id} className="flex items-center gap-2"><img src={p.images?.[0]} alt="" className="h-12 w-12 aspect-square object-cover bg-sand"/><span className="font-product-name flex-1 truncate text-sm">{p.name}</span><button onClick={()=>remove(p.tile_product_id)} className="text-xs text-cocoa/60">Remove</button></div>)}</div><button onClick={()=>setOpen(key)} className="mt-5 px-3 py-2 text-xs uppercase tracking-widest bg-gold text-sand">+ Add Product</button></section>)}</div>{open&&<div className="fixed inset-0 z-50 bg-cocoa/30 grid place-items-center p-5" onClick={()=>setOpen(null)}><div className="w-full max-w-2xl max-h-[80vh] overflow-hidden bg-shell flex flex-col" onClick={e=>e.stopPropagation()}><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search products..." className="m-4 border border-cocoa/25 bg-sand p-3 text-sm outline-none focus:border-gold"/><div className="flex-1 overflow-y-auto space-y-2 p-3">{matches.map(p=><CollectionProductOption key={p.id} product={p} selected={(tileProducts[open]||[]).some(item=>item.id===p.id)} onChoose={()=>add(p)} onSaved={load}/>)}{matches.length===0&&<p className="py-12 text-center text-sm text-cocoa/60">No matches.</p>}</div></div></div>}</div>;
}

function TileLabelForm({ tile, onSave }) {
 const [label,setLabel]=useState(tile?.label||""),[saving,setSaving]=useState(false);
 useEffect(()=>{setLabel(tile?.label||"");},[tile?.label]);
 const save=async event=>{event.preventDefault();setSaving(true);try{await onSave(tile.tile_key,label.trim());}finally{setSaving(false);}};
 return <form onSubmit={save} className="space-y-2"><label className="block text-xs uppercase tracking-widest text-cocoa/60" htmlFor={`tile-label-${tile?.tile_key}`}>Label</label><div className="flex gap-2"><input id={`tile-label-${tile?.tile_key}`} required value={label} onChange={event=>setLabel(event.target.value)} className="min-w-0 flex-1 border border-cocoa/25 bg-sand px-2 py-1 text-sm outline-none focus:border-gold"/><button type="submit" disabled={!tile||saving} className="bg-gold px-2 py-1 text-xs text-sand">{saving?"Saving...":"Save"}</button></div></form>;
}

function CollectionProductOption({ product, selected, onChoose, onSaved }) {
 const [editing,setEditing]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const [form,setForm]=useState({name:product.name,price:product.price,image_url:product.images?.[0]||""});
 useEffect(()=>{if(!editing)setForm({name:product.name,price:product.price,image_url:product.images?.[0]||""});},[editing,product]);
 const save=async event=>{event.preventDefault();event.stopPropagation();setSaving(true);setError("");try{await adminUpdateProduct(product.id,{name:form.name.trim(),price:Number(form.price),existingImages:form.image_url.trim()?[form.image_url.trim()]:[]});setEditing(false);await onSaved();}catch(err){setError(err.message||"Could not update product.");}finally{setSaving(false);}};
 if(editing)return <form onSubmit={save} onClick={event=>event.stopPropagation()} className="border border-gold bg-sand p-3 space-y-2"><div className="grid gap-2 sm:grid-cols-[1fr_9rem]"><input required value={form.name} onChange={event=>setForm({...form,name:event.target.value})} className="border border-cocoa/25 bg-shell px-2 py-1 text-sm outline-none focus:border-gold" aria-label="Product name"/><input required min="0" step="0.01" type="number" value={form.price} onChange={event=>setForm({...form,price:event.target.value})} className="border border-cocoa/25 bg-shell px-2 py-1 text-sm outline-none focus:border-gold" aria-label="Product price"/></div><input value={form.image_url} onChange={event=>setForm({...form,image_url:event.target.value})} placeholder="Image URL" className="w-full border border-cocoa/25 bg-shell px-2 py-1 text-sm outline-none focus:border-gold" aria-label="Product image URL"/>{error&&<p className="text-xs text-red-700">{error}</p>}<div className="flex justify-end gap-2"><button type="button" onClick={()=>setEditing(false)} className="px-2 py-1 text-xs text-cocoa/60">Cancel</button><button type="submit" disabled={saving} className="bg-gold px-3 py-1 text-xs text-sand">{saving?"Saving...":"Save"}</button></div></form>;
 return <div role="button" tabIndex={0} onClick={onChoose} onKeyDown={event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();onChoose();}}} aria-pressed={selected} className={`flex w-full items-center gap-3 border border-l-4 bg-sand p-2 text-left transition-colors ${selected?"border-gold border-l-gold bg-gold/10":"border-cocoa/10 border-l-transparent hover:border-gold/60"}`}><div className="h-16 w-16 shrink-0 overflow-hidden bg-shell">{product.images?.[0]?<img src={product.images[0]} alt={product.name} onError={event=>{event.currentTarget.style.display="none";event.currentTarget.nextElementSibling.style.display="flex";}} className="h-full w-full object-cover"/>:<div className="flex h-full w-full items-center justify-center text-cocoa/45"><ImageOff size={18} aria-hidden="true"/></div>}<div className="hidden h-full w-full items-center justify-center text-cocoa/45"><ImageOff size={18} aria-hidden="true"/></div></div><div className="min-w-0 flex-1"><p className="truncate font-display text-base leading-tight text-cocoa">{product.name}</p><p className="mt-1 text-xs tracking-[.08em] text-cocoa/70">₹{Number(product.price).toLocaleString("en-IN")}</p></div>{selected&&<span className="text-xs uppercase tracking-widest text-gold">Selected</span>}<button type="button" onClick={event=>{event.stopPropagation();setEditing(true);}} className="shrink-0 p-2 text-cocoa/60 hover:text-gold" aria-label={`Edit ${product.name}`}><Edit size={16}/></button></div>;
}